# Generated by Django 4.1.7 on 2024-01-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_initial'),
    ]

    operations = [
    ]
